-- AlterTable
ALTER TABLE "Purchases" ALTER COLUMN "balance" DROP DEFAULT,
ALTER COLUMN "purchase_date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Sales" ALTER COLUMN "total" DROP DEFAULT,
ALTER COLUMN "sales_date" SET DEFAULT CURRENT_TIMESTAMP;
